using BuberBreakfast.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BuberBreakfast.Persistence.Configurations;

public class BreakfastConfigurations : IEntityTypeConfiguration<Breakfast>
{
    // This maps the Model to a Database layer
    // EF uses this to create migration files. It's not used for validation.
    public void Configure(EntityTypeBuilder<Breakfast> builder)
    {
        // This is set to explicitly let EF know that we have our own key and (in this case) 
        // that we don't need an autogenerated column on the Id property.
        // If we don't set this, EF will automagically make Id the PK and set it to autogenerate
        builder.HasKey(b => b.Id);
        
        builder.Property(b => b.Name).HasMaxLength(Breakfast.MaxNameLength);
        
        builder.Property(b => b.Description).HasMaxLength(Breakfast.MaxDescriptionLength);
        
        // Savory is List<string>.
        // HasConversion handle de/serialization of the values
        builder.Property(b => b.Savory).HasConversion(
            v => string.Join(',', v), 
            v => v.Split(',', StringSplitOptions.RemoveEmptyEntries).ToList()); 
        
        // Sweet is List<string>.
        // HasConversion handle de/serialization of the values
        builder.Property(b => b.Sweet).HasConversion(
            v => string.Join(',', v), 
            v => v.Split(',', StringSplitOptions.RemoveEmptyEntries).ToList());
    }
}